services:
  # --- HEDERA OPERATOR ---
  # Runs all engines: Approver, Streamer, and Converter for Hedera
  hedera-operator:
    container_name: hedera-operator
    image: renrensan/paradapp-interoperability-service
    build: .
    command:
      [
        "--mode",
        "operator",
        "--src",
        "hedera",
        "--engine",
        "all",
        "--watch-sources",
        "eth",
        "base",
      ]
    env_file: .env
    environment:
      SQLITE_DB_DIR: "/app/data"
    volumes:
      - hedera_data:/app/data
    restart: unless-stopped

  # --- ETHEREUM OPERATOR ---
  # Runs all engines: Approver, Streamer, and Converter for Ethereum
  ethereum-operator:
    container_name: ethereum-operator
    image: renrensan/paradapp-interoperability-service
    command:
      [
        "--mode",
        "operator",
        "--src",
        "eth",
        "--engine",
        "all",
        "--watch-sources",
        "hedera",
      ]
    env_file: .env
    environment:
      SQLITE_DB_DIR: "/app/data"
    volumes:
      - ethereum_data:/app/data
    restart: unless-stopped

volumes:
  hedera_data:
  ethereum_data:
